<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>


    <xacro:property name="chassis_length" value="0.6"/>
    <xacro:property name="chassis_width" value="0.265"/>
    <xacro:property name="chassis_height" value="0.15"/>
    <xacro:property name="chassis_mass" value="5"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_thickness" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="rear_wheel_offset_x" value="0.5"/>
    <xacro:property name="rear_wheel_offset_y" value="0.2"/>
    <xacro:property name="front_wheel_offset_x" value="0.1"/>
    <xacro:property name="front_wheel_offset_y" value="0.2"/>
    <xacro:property name="fork_length" value="0.25"/>
    <xacro:property name="fork_width" value="0.02"/>
    <xacro:property name="fork_thickness" value="0.02"/>
    <xacro:property name="fork_mass" value="0.01"/>
    <xacro:property name="fork_lift_mass" value="1.0"/>
    <xacro:property name="mast_height" value="0.5"/>
    <xacro:property name="mast_width" value="0.02"/>
    <xacro:property name="mast_mass" value="0.1"/>
    <xacro:property name="carriage_length" value="0.025"/>
    <xacro:property name="carriage_width" value="0.2"/>
    <xacro:property name="carriage_thickness" value="0.02"/>
    <xacro:property name="carriage_mass" value="0.1"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-rear_wheel_offset_x} 0 ${wheel_radius}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>
    

    <!-- CABIN LINK -->


    <joint name="cabin_joint" type="fixed">
        <parent link="chassis"/>
        <child link="cabin"/>
        <origin xyz="0 0 0"/>
    </joint>

    <link name="cabin">

        <visual>
            <origin xyz="${chassis_length*0.6} 0 ${chassis_height*1.5}" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length/2} ${chassis_width/2} ${chassis_height*2}"/>
            </geometry>
            <material name="orange"/>
        </visual>

        <collision>
            <origin xyz="${chassis_length*0.6} 0 ${chassis_height*1.5}" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_length/2} ${chassis_width/2} ${chassis_height*2}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="1.0" x="${chassis_length/2}" y="${chassis_width/2}" z="${chassis_height*2}">
            <origin xyz="${chassis_length*0.6} 0 ${chassis_height*1.5}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>


    <!-- RIGHT REAR STEERING JOINT -->


    <joint name="right_rear_steer_joint" type="revolute">
        <parent link="chassis"/>
        <child link="right_rear_wheel_steer"/>
        <origin xyz="${rear_wheel_offset_x} ${rear_wheel_offset_y} 0" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-0.5" upper="0.5" effort="5.0" velocity="1.0"/>
    </joint>


    <link name="right_rear_wheel_steer">
        <visual>
            <geometry><box size="0.01 0.01 0.01"/></geometry> <!-- dummy link -->
        </visual>
        <collision>
            <geometry><box size="0.01 0.01 0.01"/></geometry> 
        </collision>
        <inertial>
            <mass value="0.01"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
    </link>


    <!-- RIGHT REAR WHEEL -->
    

    <joint name="right_rear_wheel_joint" type="revolute">
        <parent link="right_rear_wheel_steer"/>
        <child link="right_rear_wheel"/>
        <origin xyz="0 0 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/> 
        <limit lower="-1000" upper="1000" effort="0.0" velocity="1000"/> <!-- essentially free rotation -->
        <dynamics damping="0.05" friction="0.0"/> <!-- small damping to stabilize -->
    </joint>

    <link name="right_rear_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <surface>
                <friction>
                    <ode>
                        <mu>5.0</mu>       <!-- longitudinal friction -->
                        <mu2>5.0</mu2>     <!-- lateral friction -->
                        <slip1>0.0</slip1>
                        <slip2>0.0</slip2>
                    </ode>
                </friction>
            </surface>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <!-- LEFT REAR STEERING JOINT -->


    <joint name="left_rear_steer_joint" type="revolute">
        <parent link="chassis"/>
        <child link="left_rear_wheel_steer"/>
        <origin xyz="${rear_wheel_offset_x} ${-rear_wheel_offset_y} 0" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-0.5" upper="0.5" effort="5.0" velocity="1.0"/>
    </joint>


    <link name="left_rear_wheel_steer">
        <visual>
            <geometry><box size="0.01 0.01 0.01"/></geometry> <!-- dummy link -->
        </visual>
        <collision>
            <geometry><box size="0.01 0.01 0.01"/></geometry> 
        </collision>
        <inertial>
            <mass value="0.01"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
    </link>


    <!-- LEFT REAR WHEEL LINK -->


    <joint name="left_rear_wheel_joint" type="revolute">
        <parent link="left_rear_wheel_steer"/>
        <child link="left_rear_wheel"/>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
        <limit lower="-1000" upper="1000" effort="0.0" velocity="1000"/> <!-- essentially free rotation -->
        <dynamics damping="0.05" friction="0.0"/> <!-- small damping to stabilize -->
    </joint>

    <link name="left_rear_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <surface>
                <friction>
                    <ode>
                        <mu>5.0</mu>       <!-- longitudinal friction -->
                        <mu2>5.0</mu2>     <!-- lateral friction -->
                        <slip1>0.0</slip1>
                        <slip2>0.0</slip2>
                    </ode>
                </friction>
            </surface>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_rear_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>


    <!-- right FRONT WHEEL LINK -->


    <joint name="right_front_wheel_joint" type="continuous">
        <parent link="chassis"/>
        <child link="right_front_wheel"/>
        <origin xyz="${front_wheel_offset_x} ${front_wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="right_front_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <!-- <surface>
                <friction>
                    <ode>
                        <mu>0.01</mu>
                        <mu2>0.1</mu2>
                    </ode>
                </friction>
            </surface> -->
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_front_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>


    <!-- left FRONT WHEEL LINK -->

    <joint name="left_front_wheel_joint" type="continuous">
        <parent link="chassis"/>
        <child link="left_front_wheel"/>
        <origin xyz="${front_wheel_offset_x} ${-front_wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="left_front_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <!-- <surface>
                <friction>
                    <ode>
                        <mu>0.01</mu>
                        <mu2>0.1</mu2>
                    </ode>
                </friction>
            </surface> -->
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_front_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>


    <!-- MAST LINK -->


    <link name="mast">
        <visual>
            <geometry>
                <box size="${mast_width} ${mast_width} ${mast_height}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <box size="${mast_width} ${mast_width} ${mast_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${mast_mass}" x="${mast_width}" y="${mast_width}" z="${mast_height}">
            <origin xyz="${mast_width/2} 0 ${mast_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="mast_joint" type="fixed">
        <parent link="chassis"/>
        <child link="mast"/>
        <origin xyz="${-mast_width/2} 0 ${wheel_radius*0.1+chassis_height}" rpy="0 0 0"/>
    </joint>


    <!-- FORK CARRIAGE -->


    <link name="fork_carriage">
        <visual>
            <geometry>
                <box size="${carriage_length} ${carriage_width} ${carriage_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${carriage_length} ${carriage_width} ${carriage_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${carriage_mass}" x="${carriage_length}" y="${carriage_width}" z="${carriage_thickness}">
            <origin xyz="${carriage_length/2} 0 ${carriage_thickness/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="fork_carriage_joint" type="prismatic">
        <parent link="mast"/>
        <child link="fork_carriage"/>
        <origin xyz="-${mast_width/2 + carriage_length/2} 0 ${-mast_height/2+carriage_thickness}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="0" upper="${mast_height}" effort="10" velocity="0.1"/>
    </joint>


    <!-- right FORK -->


    <link name="fork_right">
        <visual>
            <geometry>
                <box size="${fork_length} ${fork_width} ${fork_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <box size="${fork_length} ${fork_width} ${fork_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${fork_mass}" x="${fork_length}" y="${fork_width}" z="${fork_thickness}">
        <origin xyz="${fork_length/2} 0 0"/>
        </xacro:inertial_box>
    </link>
    <joint name="fork_right_joint" type="fixed">
        <parent link="fork_carriage"/>
        <child link="fork_right"/>
        <origin xyz="${-fork_length/2+carriage_length/2} ${(carriage_width/2+fork_width)} 0" rpy="0 0 ${pi}"/>
    </joint>


    <!-- left FORK -->


    <link name="fork_left">
        <visual>
            <geometry>
                <box size="${fork_length} ${fork_width} ${fork_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <box size="${fork_length} ${fork_width} ${fork_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${fork_mass}" x="${fork_length}" y="${fork_width}" z="${fork_thickness}">
        <origin xyz="${fork_length/2} 0 0"/>
        </xacro:inertial_box>
    </link>
    <joint name="fork_left_joint" type="fixed">
        <parent link="fork_carriage"/>
        <child link="fork_left"/>
        <origin xyz="${-fork_length/2+carriage_length/2} ${-(carriage_width/2+fork_width)} 0" rpy="0 0 ${pi}"/>
    </joint>



</robot>